name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "211.230.110.231:50008"
UUID = "53145092-d560-4e0a-877b-29d87a3b095d"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
